// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enabled": boolean;
      "types.highlight": boolean;
      "types.underline": boolean;
      "types.note": boolean;
      "types.text": boolean;
      "types.image": boolean;
      "compactNoteIcons": boolean;
      "ai.enabled": boolean;
      "ai.webChatEnabled": boolean;
      "ai.apiProtocol": string;
      "ai.apiBase": string;
      "ai.apiKey": string;
      "ai.model": string;
      "ai.color": string;
      "ai.maxAnnotations": number;
      "ai.customInstructions": string;
    };
  }
}
